// frontend/src/app/components/metric/metric.component.ts
import { Component, Input } from '@angular/core';
import { ProgressBarComponent } from '../progress-bar/progress-bar.component';

@Component({
  selector: 'app-metric',
  standalone: true,
  imports: [ProgressBarComponent],
  template: `
    <section class="flex flex-col gap-3 p-4">
      <div class="flex gap-6 justify-between">
        <p class="text-white text-base font-medium leading-normal">{{ title }}</p>
        <p class="text-white text-sm font-normal leading-normal">{{ percent }}%</p>
      </div>
      <app-progress-bar [percent]="percent" />
      <p class="text-[#92adc9] text-sm font-normal leading-normal">{{ caption }}</p>
    </section>
  `,
})
export class MetricComponent {
  @Input() title = '';
  @Input() percent = 0;
  @Input() caption = '';
}

// app/src/components/Metric.tsx
import ProgressBar from "./ProgressBar";

interface MetricProps {
  title: string;
  percent: number;
  caption: string;
}

export default function Metric({ title, percent, caption }: MetricProps) {
  return (
    <section className="flex flex-col gap-3 p-4">
      <div className="flex gap-6 justify-between">
        <p className="text-white text-base font-medium leading-normal">
          {title}
        </p>
        <p className="text-white text-sm font-normal leading-normal">
          {percent}%
        </p>
      </div>
      <ProgressBar percent={percent} />
      <p className="text-[#92adc9] text-sm font-normal leading-normal">
        {caption}
      </p>
    </section>
  );
}
