// app/src/components/ProgressBar.tsx
interface ProgressBarProps {
  percent: number; // 0-100
  trackClassName?: string;
  barClassName?: string;
}

export default function ProgressBar({
  percent,
  trackClassName = "bg-[#324d67]",
  barClassName = "bg-[#1380ec]",
}: ProgressBarProps) {
  const clamped = Math.max(0, Math.min(100, percent));
  return (
    <div className={`rounded ${trackClassName}`}>
      <div
        className={`h-2 rounded ${barClassName}`}
        style={{ width: `${clamped}%` }}
      />
    </div>
  );
}

// frontend/src/app/components/progress-bar/progress-bar.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-progress-bar',
  standalone: true,
  template: `
    <div class="rounded bg-[#324d67] w-full">
      <div class="h-2 rounded bg-[#1380ec]" [style.width.%]="clamped"></div>
    </div>
  `,
})
export class ProgressBarComponent {
  @Input() percent = 0;
  get clamped() { return Math.max(0, Math.min(100, this.percent)); }
}
